"""change table names

Revision ID: c24d96a20a6d
Revises: 7e62a9ff931c
Create Date: 2019-11-29 14:05:58.096623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c24d96a20a6d'
down_revision = '7e62a9ff931c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pass_secure', sa.String(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=True),
    sa.Column('posted_by', sa.String(length=255), nullable=True),
    sa.Column('posted_on', sa.DateTime(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('commentT')
    op.drop_index('ix_userT_email', table_name='userT')
    op.drop_index('ix_userT_username', table_name='userT')
    op.drop_table('userT')
    op.drop_table('blogT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogT',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"blogT_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posted_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userT.id'], name='blogT_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blogT_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('userT',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userT_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pass_secure', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='userT_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_userT_username', 'userT', ['username'], unique=False)
    op.create_index('ix_userT_email', 'userT', ['email'], unique=True)
    op.create_table('commentT',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"commentT_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('body', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('posted_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('posted_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogT.id'], name='commentT_blog_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='commentT_pkey')
    )
    op.drop_table('comments')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
